name: Sync to GranniesLV

on:
  push:
    branches:
      - main  # vai jebkura cita nozīmīga filiāle, kuru tu izmanto

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout eamon9 repository
      uses: actions/checkout@v2

    - name: Set up SSH key for GranniesLV
      run: |
        mkdir -p ~/.ssh
        echo "$GRANNIES_SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Push to GranniesLV repository
      run: |
        git remote add grannieslv git@github.com:GranniesLV/granniesWebPage.git
        git push grannieslv main --force
      env:
        GRANNIES_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDjmePdUw9h90novCdgD/Rm8Z3OGFym6u4okrpHMk5x0SHmSTH+HUycWgksxsDx/3/f26pkJzCDoe/0kXAvF/fRGhvWkuRz4vjGr+32TUK6NjbH9zBXHX8heIjNgVxoHPL2hfrpa2fvVTx1DKxvzEwInhwPNs4Hw5D5oGnJAfZ5JOym5D5ohbzClKApZB3QiqJUSf+9hPW7xCbRjbysC7cQakblpOe4dYe4Hn0uiuHZJe6qWXxFLFHbe0zUa4JYQLnUbLyn5rv/N8rwtCJreXJFaadodJurTwSMpTWmob6KQv0vS3WU4cSbLKc90p0LMV7wyhEcsUxbtJeKaIwIBC3/VES0GAAlvvGbtBDxvhNCfqcMVT16ZbLX+i9umZbflLt6DnWy87HQMCs8oFPeLGNErVO3ObdRpIaDAE0MtInS3Ad6GA2tHL32buPzUEg45i23m6/HE9aDUZjjTCTx6MUGaN95i3r83am6W3zJ5DUeOOgw3pseqDVzE6/ynh/KpM= qwer@DoGR-MBP # Tava SSH atslēga šeit
